# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 317)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.first_user_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.first_user_label.setGeometry(QtCore.QRect(30, 40, 55, 16))
        self.first_user_label.setObjectName("first_user_label")
        self.first_password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.first_password_label.setGeometry(QtCore.QRect(30, 80, 55, 16))
        self.first_password_label.setObjectName("first_password_label")
        self.first_user_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.first_user_entry.setGeometry(QtCore.QRect(100, 40, 211, 22))
        self.first_user_entry.setObjectName("first_user_entry")
        self.first_password_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.first_password_entry.setGeometry(QtCore.QRect(100, 80, 211, 22))
        self.first_password_entry.setObjectName("first_password_entry")
        self.acc_create_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.acc_create_button.setGeometry(QtCore.QRect(40, 140, 111, 28))
        self.acc_create_button.setObjectName("acc_create_button")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(212, 140, 111, 28))
        self.login_button.setObjectName("login_button")
        self.application_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.application_label.setGeometry(QtCore.QRect(140, 10, 121, 21))
        self.application_label.setObjectName("application_label")
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(100, 180, 231, 51))
        self.status_label.setObjectName("status_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.first_user_label.setText(_translate("MainWindow", "Username"))
        self.first_password_label.setText(_translate("MainWindow", "Password"))
        self.acc_create_button.setText(_translate("MainWindow", "Create Account"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.application_label.setText(_translate("MainWindow", "Password Manager"))
        self.status_label.setText(_translate("MainWindow", "Please Create an Account or Login"))

        self.first_password_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)