# Form implementation generated from reading ui file 'second_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(523, 317)
        self.centralwidget = QtWidgets.QWidget(parent=SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.website_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.website_entry.setGeometry(QtCore.QRect(90, 20, 191, 22))
        self.website_entry.setObjectName("website_entry")
        self.search_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(290, 20, 93, 28))
        self.search_button.setObjectName("search_button")
        self.details_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.details_label.setGeometry(QtCore.QRect(90, 49, 201, 71))
        self.details_label.setObjectName("details_label")
        self.add_new_site_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_new_site_button.setGeometry(QtCore.QRect(40, 140, 93, 28))
        self.add_new_site_button.setObjectName("add_new_site_button")
        self.exit1_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit1_button.setGeometry(QtCore.QRect(220, 140, 93, 28))
        self.exit1_button.setObjectName("exit1_button")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 26))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "SecondWindow"))
        self.search_button.setText(_translate("SecondWindow", "Search"))
        self.details_label.setText(_translate("SecondWindow", "Enter a website above or add a new one"))
        self.add_new_site_button.setText(_translate("SecondWindow", "Add New"))
        self.exit1_button.setText(_translate("SecondWindow", "Exit"))

        self.details_label.setWordWrap(True)