# Form implementation generated from reading ui file 'third_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ThirdWindow(object):
    def setupUi(self, ThirdWindow):
        ThirdWindow.setObjectName("ThirdWindow")
        ThirdWindow.resize(416, 274)
        self.centralwidget = QtWidgets.QWidget(parent=ThirdWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.website_name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.website_name_label.setGeometry(QtCore.QRect(40, 10, 71, 16))
        self.website_name_label.setObjectName("website_name_label")
        self.second_username_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.second_username_label.setGeometry(QtCore.QRect(40, 50, 61, 16))
        self.second_username_label.setObjectName("second_username_label")
        self.second_password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.second_password_label.setGeometry(QtCore.QRect(40, 90, 55, 16))
        self.second_password_label.setObjectName("second_password_label")
        self.website_name_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.website_name_entry.setGeometry(QtCore.QRect(120, 10, 211, 22))
        self.website_name_entry.setObjectName("website_name_entry")
        self.second_username_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.second_username_entry.setGeometry(QtCore.QRect(120, 50, 211, 22))
        self.second_username_entry.setObjectName("second_username_entry")
        self.second_password_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.second_password_entry.setGeometry(QtCore.QRect(120, 90, 211, 22))
        self.second_password_entry.setObjectName("second_password_entry")
        self.new_website_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.new_website_label.setGeometry(QtCore.QRect(120, 109, 211, 51))
        self.new_website_label.setObjectName("new_website_label")
        self.enter_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(30, 160, 93, 28))
        self.enter_button.setObjectName("enter_button")
        self.back_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(230, 160, 93, 28))
        self.back_button.setObjectName("back_button")
        ThirdWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ThirdWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 26))
        self.menubar.setObjectName("menubar")
        ThirdWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ThirdWindow)
        self.statusbar.setObjectName("statusbar")
        ThirdWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ThirdWindow)
        QtCore.QMetaObject.connectSlotsByName(ThirdWindow)

    def retranslateUi(self, ThirdWindow):
        _translate = QtCore.QCoreApplication.translate
        ThirdWindow.setWindowTitle(_translate("ThirdWindow", "ThirdWindow"))
        self.website_name_label.setText(_translate("ThirdWindow", "Website Name"))
        self.second_username_label.setText(_translate("ThirdWindow", "Username"))
        self.second_password_label.setText(_translate("ThirdWindow", "Password"))
        self.new_website_label.setText(_translate("ThirdWindow", "Please enter new website details"))
        self.enter_button.setText(_translate("ThirdWindow", "Enter"))
        self.back_button.setText(_translate("ThirdWindow", "Back"))
